# Generated by Django 3.0.6 on 2020-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('B', 'Beginer'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', max_length=255)),
            ],
        ),
    ]
