# Generated by Django 3.0.6 on 2020-06-04 08:34

import Education.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=IZj8hLrkABs', validators=[django.core.validators.URLValidator, Education.models.Lecture.youtube_validator]),
            preserve_default=False,
        ),
    ]
