# Generated by Django 3.0.6 on 2020-06-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_auto_20200605_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='base_id',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginer', 'Beginer'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginer', max_length=255),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
