# Generated by Django 3.0.6 on 2020-06-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_lecture_url'),
        ('Education', '0003_auto_20200605_1206'),
    ]

    operations = [
    ]
